CREATE TABLE ACCOUNT
(
    __id INTEGER NOT NULL AUTO_INCREMENT,
    id VARCHAR(50) NOT NULL,
    client_id VARCHAR(50) NOT NULL,
    balance DECIMAL(10,2) NOT NULL,
    account_type ENUM('CHECKING', 'SAVINGS', 'FIXED') NOT NULL,
    withdraw_allowed BOOLEAN NOT NULL,
    CONSTRAINT PK_Account PRIMARY KEY (__id)
);

CREATE TABLE TRANSACTION
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    account_id VARCHAR(50) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_Transaction PRIMARY KEY (id)
);